#!/system/bin/sh
# SuperMemory tweak by aris setiawan (aris10@XDA)

echo 3 > /proc/sys/vm/page-cluster
setprop ro.FOREGROUND_APP_MEM 1280
setprop ro.VISIBLE_APP_MEM 2560
setprop ro.PERCEPTIBLE_APP_MEM 3840
setprop ro.HEAVY_WEIGHT_APP_MEM 6400
setprop ro.SECONDARY_SERVER_MEM 7680
setprop ro.BACKUP_APP_MEM 8960
setprop ro.HOME_APP_MEM 2048
setprop ro.HIDDEN_APP_MEM 12800
setprop ro.CONTENT_PROVIDER_MEM 15360
setprop ro.EMPTY_APP_MEM 20480
setprop ro.FOREGROUND_APP_ADJ 0
setprop ro.VISIBLE_APP_ADJ 1
setprop ro.PERCEPTIBLE_APP_ADJ 2
setprop ro.HEAVY_WEIGHT_APP_ADJ 4
setprop ro.SECONDARY_SERVER_ADJ 5
setprop ro.BACKUP_APP_ADJ 6
setprop ro.HOME_APP_ADJ 1
setprop ro.HIDDEN_APP_MIN_ADJ 7
setprop ro.EMPTY_APP_ADJ 15